server:
  application:
    name: custom_florist
  port: 8080
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/swd392_custom_florist}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
api:
  prefix: /custom-florist
jwt:
  expiration: 86400 # 24h
  secretKey: U3t9aQv9tqdw/mwvxDrl4ebJKiurzORBmS1gzYKDeT+zJOTg0xAauB7HpLCYasbo
open:
  api:
    title: Custom Florist API
    version: 1.0.0
    description: Meta API service
    serverUrl: http://localhost:8080
    serverName: server test
payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:8080
    tmnCode: ZYVDT6EC
    secretKey: O0FQ4IFU6EO79AV2YPTWMKCGK7T3WROH
    version: 2.1.0
    command: pay
    orderType: Flower